# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

## Example configuration for sending data to your own OTLP HTTP backend
## Note: the spanmetrics exporter must be included in the exporters array
## if overriding the traces pipeline.
##
  exporters:
    file/traces:
      path: /etc/data/traces.pb
      format: proto
    file/metrics:
      path: /etc/data/metrics.pb
      format: proto
    file/logs:
      path: /etc/data/logs.pb
      format: proto

  service:
    pipelines:
      traces:
        exporters: [otlp, debug, spanmetrics, file/traces]
      metrics:
        exporters: [otlphttp/prometheus, debug, file/metrics]
      logs:
        exporters: [otlp/logs, debug, file/logs]
